service: chapter1
frameworkVersion: "3"

plugins:
  - serverless-pseudo-parameters
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-west-1

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello
